name: Actionlint

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
    paths:
      - ".github/actions/**"
      - ".github/workflows/**"

jobs:
  actionlint:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run actionlint
        uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-pr-review
          fail_on_error: true
